import { ProgramJob, MeetingLog } from "./types";

export const initialPrograms: Omit<ProgramJob, "id">[] = [
  {
    no: 1,
    topic: "Benchmarking Konektivitas Pelabuhan (KIT Batang) ke China",
    cluster: "Corporate Insight",
    owner: "DC, DJ",
    ztRole: "Owner",
    strategicImpact: "Meningkatkan konektivitas pelabuhan KIT Batang dengan benchmark ke China",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Cover letter ke 2 perusahaan sudah terkirim (Tianjin port dan Qingdao port) per tanggal 21 mei 26, menunggu jawaban. Konfirmasi PIC Guide/ translator - Done, tinggal tunggu kepastian jadwal keberangkatan. PIC perwakilan dari DI belum ada konfirmasi. 26 Juni 2026 : belum ada update lanjut dari KBRI",
    keyIssue: "Pengiriman surat resmi ke perusahaan yang dituju terkendala belum adanya email resmi dari masing masing perusahaan",
    actionPlan: "Update rencana benchmark ke China. Senin, 15 Juni 2026 : rencana akan diskusi dengan PIC kawista terkait RAB, ittenary dll. 17 Juni 2026 : sudah dilakukan koordinasi dan sudah kirimkan nota diplomatik ke Kemenhub RRT utk minta bantu fasilitasi, namun sampai sekarang blm dapat tanggapan. (To be Confirm)",
    startDate: "2026-05-15",
    deadline: "2026-06-14",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/rWxtDgMsXXowwmg",
    notes: "Update Terakhir: Jumat, 26 Juni 2026"
  },
  {
    no: 2,
    topic: "PMO perlintasan sebidang",
    cluster: "Change Management",
    owner: "DN",
    ztRole: "Monitoring",
    strategicImpact: "Keselamatan perlintasan sebidang prioritas di 190 lokasi. End Product: 1687 Perlintasan dibangun",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "25 Juni 2026: 1. Percepatan Program Prioritas Perlintasan (penutupan mencapai 91%). 2. Sinkronisasi Konstruksi dan Rekrutmen 746 PJL (rekrutmen PJL berjalan, sertifikasi dipercepat, siap bertugas September 2026). 3. Finalisasi Lokasi dan Pendanaan.",
    keyIssue: "Unit ZT tidak pernah dilibatkan secara langsung dalam kegiatan rapat / pembahasan",
    actionPlan: "Unit ZT tetap monitoring dan melaporkan kepada DZ",
    startDate: "2026-04-01",
    deadline: "",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "High",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/f/440418727",
    notes: "Update Terakhir: Jumat, 26 Juni 2026"
  },
  {
    no: 3,
    topic: "Penguatan function SDM sebagai driver perusahaan",
    cluster: "Strategic Transformation",
    owner: "DR, DS",
    ztRole: "Contributing",
    strategicImpact: "Kesehatan fisik & mental merupakan faktor utama keselamatan operasional. Intervensi SDM perlu berfokus pada pencegahan dan penguatan leadership.",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "Sudah dilakukan audiensi dengan tim Home, selanjutnya perlu dilakukan audiensi lanjutan dengan tim Kesehatan, HSO. 19 Juni 2026: unit assesment telah melakukan survey terhadap pegawai dilingkungan kerja unit operasional (crew & non crew).",
    keyIssue: "Kessesuaian manpower planning vs kebutuhan riil user. Metode penerjemahan kebutuhan user menjadi kriteria asesmen. Potensi subjektivitas akibat fleksibilitas rekrutmen. Konsistensi standar seleksi antar unit. Reposisi SDM JOSS belum maksimal.",
    actionPlan: "Next narasumber : HSO, Asesor, orang Kesehatan. 03 Jul 26 : Rencana paparan hasil kajian (Plan Senin, 06 Jul 26)",
    startDate: "2026-05-01",
    deadline: "2026-06-15",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/ebESNJMeXfpjneg",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 4,
    topic: "MRO Balaiyasa Depo",
    cluster: "Strategic Transformation",
    owner: "DH",
    ztRole: "Contributing",
    strategicImpact: "SBU sudah operasional divisi maintenance sarana",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "5 Juni 2026: Process penyusunan tim transisi. 10 juni 2026: Rencana kick off meeting pembentukan penyusunan ortala divisi maintenance sarana dibatalkan. 26 Juni 2026 : Pembahasan Lanjutan Penyusunan Organisasi di Balaiyasa Yogyakarta, hasil belum diketahui, Tim ZT tidak diundang.",
    keyIssue: "Pembahasan Lanjutan Penyusunan Organisasi dan Tata Kelola Divisi Maintenance Sarana PT KAI (Persero) tidak mengundang Tim ZT",
    actionPlan: "Monitoring penyusunan organisasi SBU MRO",
    startDate: "2026-06-01",
    deadline: "2026-07-01",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/ebESNJMeXfpjneg",
    notes: "Update Terakhir: Senin, 6 Juli 2026"
  },
  {
    no: 5,
    topic: "Perdir Tata Kelola Investasi",
    cluster: "Investment Governance",
    owner: "DI",
    ztRole: "Monitoring",
    strategicImpact: "Perdir",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Perubahan nomenklatur baru hasil dari RUPS, sehingga terbentuk penggabungan direktorat operasi, prasarana dan keselamatan.",
    keyIssue: "Adanya Pembahasan SO baru, menyebabkan kemungkinan adanya pembaharuan pada peraturan tentang keselamatan dan operasional",
    actionPlan: "Menunggu update lebih lanjut",
    deadline: "2026-07-31",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZT/ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/RFZNWB7Wf3R38j3",
    notes: "Update Terakhir: Senin, 6 Juli 2026"
  },
  {
    no: 6,
    topic: "Penguatan fungsi Safety",
    cluster: "Change Management",
    owner: "DF",
    ztRole: "Owner",
    strategicImpact: "Draf strukturisasi di Daop/ Divre Kelas A: - Operasional - Safety & security",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Perubahan nomenklatur baru hasil dari RUPS, sehingga terbentuk penggabungan direktorat operasi, prasarana dan keselamatan.",
    keyIssue: "Adanya Pembahasan SO baru, menyebabkan kemungkinan adanya pembaharuan pada peraturan tentang keselamatan dan operasional",
    actionPlan: "Menunggu update lebih lanjut",
    deadline: "2026-07-01",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/ebESNJMeXfpjneg",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 7,
    topic: "Review Perdir & Produk Regulasi terkait Probis (termasuk SLA)",
    cluster: "Investment Governance",
    owner: "DI",
    ztRole: "Monitoring",
    strategicImpact: "Probis tidak terganggu dengan Perdir/Produk Regulasi yang ada",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "9 juni 2026: pembahasan draft awal kajian review perdir dan SLA. 26 Juni 2026 : akan dipresentasikan ke Pak ZT pada tanggal 29 Juni 2026. 3 Jul 26 : Proses revisi materi.",
    keyIssue: "Perlu diputuskan untuk piloting: by unit kerja atau by peraturan (diputuskan by peraturan)",
    actionPlan: "Identifikasi peraturan yang perlu penyesuaian",
    deadline: "2026-06-15",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/f/449955424",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 8,
    topic: "SO ZT",
    cluster: "Strategic Transformation",
    owner: "DC",
    ztRole: "Owner",
    strategicImpact: "Perdir penyesuaian SO ZT di bawah DZ",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Red",
    currentMilestone: "17 Juni 2026 Pendetailan Output hingga level Specialist dan KPI 3. 24 Juni 2026 Desain Struktur Organisasi dan Tugas Pokok dan Fungsi (Tupoksi). Update Unit HSO: Dalam proses reviu proses bisnis based on meeting SCB ZT HSO. ZT sudah mengirim rds ke DZ pada tanggal 23 Juni 2026. 01 Juli 2026: HSO mengusulkan untuk direschedule.",
    keyIssue: "Presentasi telah disampaikan oleh unit ZT, menunggu review dari HSO. Perlu pembahasan tentang tata kelola Heritage karena ada potensi tumpang tindih fungsi dengan divisi properti.",
    actionPlan: "17 Juni 2026, Pembahasan lanjutan dengan HSO. 03 Jul 26 : Plan melakukan pembahasan dengan Unit HSO Selasa, 07 Jul 26",
    deadline: "2026-06-15",
    decisionNeeded: "Yes",
    dzIntervention: "Persetujuan Usulan Perubahan SO",
    ztPic: "ZT/ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/ebESNJMeXfpjneg",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 9,
    topic: "Format Kajian",
    cluster: "Change Management",
    owner: "DC, DJ, DN, DR, DS, DH, DI, DF",
    ztRole: "Owner",
    strategicImpact: "Format kajian terstandar",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "8 Juni 2026: Draft format kajian telah dibuat. 26 Juni 2026: Pembahasan internal draft format kajian.",
    keyIssue: "Perlu kajian untuk menentukan skor parameter dalam pembuatan format kajian",
    actionPlan: "Akan dilakukan pencarian referensi penentuan skor parameter",
    deadline: "2026-05-29",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS/ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/BqoNCWq6EBdpJqB",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 10,
    topic: "Standarisasi SOP Weekly briefing",
    cluster: "Change Management",
    owner: "DC, DJ, DN, DR, DS, DH, DI, DF",
    ztRole: "Owner",
    strategicImpact: "Konsep standarisasi Weekly briefing termasuk tools",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "26 Juni 2026 : akan dipresentasikan ke ZT pada hari kamis 02 Juli 2026",
    keyIssue: "Metode, tools yang di gunakan saat briefing",
    actionPlan: "akan disusun standarisasi SOP weekly briefing. 03 Jul 26 : Plan paparan Kamis, 09 Jul 26",
    deadline: "2026-07-15",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/BqoNCWq6EBdpJqB",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 11,
    topic: "Transformasi Mindset",
    cluster: "Strategic Transformation",
    owner: "DN, DR",
    ztRole: "Contributing",
    strategicImpact: "Konsep,Target dan Alat ukur Transformasi Mindset",
    phase: "Execution",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "05 Juni 2026 : Update dengan Tim Culture, masih butuh pendetailan kajian dari ZT. 26 Juni 2026 : akan dipresentasikan ke pak ZT pada tanggal 01 Juli 2026.",
    keyIssue: "Detail implementasi alat ukur mindset",
    actionPlan: "03 Jul 26 : Plan melakukan paparan internal Rabu, 08 Jul 26",
    deadline: "2026-06-15",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/S4crHc3ZkfxZRX4",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 12,
    topic: "Transformasi Bisnis Heritage",
    cluster: "Corporate Culture",
    owner: "DS, DH",
    ztRole: "Owner",
    strategicImpact: "Konsep,Target, Action Plan",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "sudah selesai. akan dilaksanakan presentasi lanjut",
    keyIssue: "Integrasi skema bisnis wisata sejarah",
    actionPlan: "Akan dilaksanakan presentasi lanjut",
    deadline: "2026-06-15",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "High",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/y7n9PDxYWWLYZiA",
    notes: "Update Terakhir: Jumat, 26 Juni 2026"
  },
  {
    no: 13,
    topic: "Optimalisasi dan utilisasi aset heritage Daop 3",
    cluster: "Corporate Culture",
    owner: "DS, DH",
    ztRole: "Contributing",
    strategicImpact: "Penataan Stasiun Cirebon, Depo Lokomotif Cirebon, dan jembatan kereta",
    phase: "Execution",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Stasiun Cirebon: Penataan area non-aset, penataan area depan & rencana eskalator underpass, implementasi CTC. Penataan Depo Lokomotif Cirebon: Cagar Budaya, koordinasi Disbudpar. Pembongkaran jembatan KA: membuat tugu atau monumen.",
    keyIssue: "Bangunan Depo Lok, bangunan kantor Depo Lok, dan turntable di Depo Lok telah terregistrasi sebagai Objek Diduga Cagar Budaya (ODCB) di Disbudpar Kota Cirebon",
    actionPlan: "Kirim surat resmi kepada Wali Kota Cirebon mengenai rencana pekerjaan investasi Penataan Depo Lokomotif Cirebon",
    deadline: "2026-06-28",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/y7n9PDxYWWLYZiA",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 14,
    topic: "Optimalisasi dan utilisasi aset heritage Daop 4",
    cluster: "Corporate Culture",
    owner: "DS, DH",
    ztRole: "Contributing",
    strategicImpact: "Pemanfaatan optimal Lawang Sewu, Museum Ambarawa, Gedung SCS",
    phase: "Execution",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Lawang Sewu: 8 mitra sewa sharing profit. Museum Ambarawa: toilet belum memadai, armada 3 kereta, tiket offline. Gedung SCS: fondasi baik, pemeliharaan pengecatan parsial.",
    keyIssue: "Lawang Sewu: Keterbatasan Parkir. Museum Ambarawa: keterbatasan SDM teknis, pemeliharaan aset gap RKA, tidak ada aturan tertulis tanggung jawab perawatan detail. Gedung SCS: Kebocoran bangunan.",
    actionPlan: "Review porsi tanggung jawab perawatan detail KAI & Kawisata",
    deadline: "",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/y7n9PDxYWWLYZiA",
    notes: "Update Terakhir: Kamis, 11 Juni 2026"
  },
  {
    no: 15,
    topic: "KPI",
    cluster: "Corporate Insight",
    owner: "DC",
    ztRole: "Owner",
    strategicImpact: "Penyiapan data dukung KPI semester 1",
    phase: "Benefit Realization",
    progress: 10,
    statusTracker: "Green",
    currentMilestone: "26 Juni 2026 : Pembahasan penyiapan data dukung untuk semester 1. 30 Jun 26 : Melakukan meeting dengan unit ISP dan IPB untuk meminta data pendukung KPI.",
    keyIssue: "Kelengkapan data dukung KPI",
    actionPlan: "03 Jul 26 : Mempersiapkan data pendukung untuk KPI yang lain",
    deadline: "2026-06-04",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS/ZTI",
    confidence: "High",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://docs.google.com/spreadsheets/d/1stRwg3C5PQYGWuaZOtKAiY3SfTKOcfSaMQcVdZHHwbo/edit?gid=0#gid=0",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 16,
    topic: "Pembentukan MRO (Juni SO Depo dibawah Balaiyasa)",
    cluster: "Strategic Transformation",
    owner: "DH",
    ztRole: "Contributing",
    strategicImpact: "Perdir organisasi Balai Yasa dan Daop/Divre terbit",
    phase: "Execution",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "2026 06 03 SO PMO sudah terbit. Kick Off Meeting ditunda. 26 Juni 2026 : Pembahasan Lanjutan Organisasi Maintenance Sarana di Balaiyasa Yogyakarta, Tim ZT tidak diundang.",
    keyIssue: "Pembentukan PMO MRO tidak melibatkan Unit ZT. Pemahaman konsep MRO masing-masing unit belum selaras.",
    actionPlan: "Monitoring progres yang dilakukan oleh SC, SG, HC. ZT akan membuat kajian internal.",
    deadline: "2026-06-30",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/oDwrszQG5EfMPpB",
    notes: "Update Terakhir: Jumat, 26 Juni 2026"
  },
  {
    no: 17,
    topic: "Investasi Pengadaan 119 Unit Lokomotif Untuk Program Replacement BB 203, BB302/3 Dan CC 201 Tahun 2027-2031",
    cluster: "Investment Governance",
    owner: "DI, DF",
    ztRole: "Monitoring",
    strategicImpact: "Dokumen investasi 119 lok terseleasikan",
    phase: "Validasi",
    progress: 0,
    statusTracker: "Red",
    currentMilestone: "25 Jun 26 : DZ meminta kepada IS untuk membuatkan kajian second opinion tentang perbandingan biaya perawatan 119 Lok dengan jika menjadi biaya investasi 119 Lok.",
    keyIssue: "Minta dikaji ulang oleh pak Noel, kajian yang lebih komprehensif, finansial, bisnis, risiko, hukum ke tim Sarana",
    actionPlan: "Memonitor progress. Note : jangan mengorbankan preventive maintenance.",
    deadline: "",
    decisionNeeded: "Yes",
    dzIntervention: "Second Opinion Cost Analysis Review",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/f/448287892",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 18,
    topic: "Perdir Tata Kelola Investasi (On Track)",
    cluster: "Investment Governance",
    owner: "DI, DF",
    ztRole: "Contributing",
    strategicImpact: "Perdir Investasi dan Komite Investasi terbit",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "11 Juni 2026 proses sirkulir persetujuan perdir 8 dari 38 ttd sudah diselesaikan. 26 Juni 2026 : akan dipresentasikan ke Pak ZT pada tanggal 29 Juni 2026. 29 Juni 2026 : draft perdir sudah di paraf Pak ZT.",
    keyIssue: "SOP yang di kerjakan oleh unit lainnya sedang di kerjakan oleh unit terkait masing-masing. namun jika dikerjakan sendiri-sendiri maka akan terjadi miss.",
    actionPlan: "ZT akan melakukan review sebelum persetujuan. 03 Jul 26 : Melakukan bahasan dengan unit ISP, ZL, SCB dan IPB.",
    deadline: "2026-05-22",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/BqoNCWq6EBdpJqB",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 19,
    topic: "Flowchart Forum Arahan Investasi",
    cluster: "Investment Governance",
    owner: "DJ",
    ztRole: "Contributing",
    strategicImpact: "SOP terselesaikan dan terbit bersamaan dengan Perdir Investaso",
    phase: "Execution",
    progress: 10,
    statusTracker: "Yellow",
    currentMilestone: "10 Juni 2026: Rapat dengan HSO & SCB membahas tentang konsep forum arahan investasi. 26 Juni 2026: akan dipresentasikan ke ZT. 01 Juli 2026: Undangan pembahasan.",
    keyIssue: "Draft flowchart belum sesuai dengan konsep forum arahan investasi (output belum dengan konsep dari tim probis, dimana output forum arahan investasi nantinya adalah arah investasi bukan berupa roadmap)",
    actionPlan: "Akan dilakukan penyesuaian flowchart forum arahan investasi. 03 Jul 26 : Melakukan bahasan dengan unit ISP, ZL, SCB, FS dan IPB.",
    deadline: "2026-06-19",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS/ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/BqoNCWq6EBdpJqB",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 20,
    topic: "Investasi Kramasan (KALOG)",
    cluster: "Investment Governance",
    owner: "DN, DS",
    ztRole: "Contributing",
    strategicImpact: "Investasi kramasan berjalan kembali dan bisa terselesaikan",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Red",
    currentMilestone: "23 April 2026: Menunggu Approval dana Chip in. 26 Mei 2026: Kajian percepatan CRCC masih banyak celah. KAI terbitkan guarantee letter 2 Juni. IS hitung ulang kelayakan.",
    keyIssue: "- Ketidaktersediaan dana konstruksi. - Percepatan proses pembebasan sisa lahan (6% dri 11 Ha) dan proses sertifikat lahan.",
    actionPlan: "03 Jul 26 : Follow Up ke KALOG prihal update inveatsi kramasan (Internal ZT)",
    deadline: "",
    decisionNeeded: "Yes",
    dzIntervention: "Guarantee Letter & Funding Approval",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/f/448287856",
    notes: "Update Terakhir: Senin, 6 Juli 2026"
  },
  {
    no: 21,
    topic: "Implementasi IBM Maximo",
    cluster: "Strategic Transformation",
    owner: "DI",
    ztRole: "Owner",
    strategicImpact: "Penyusunan draf kajian implementasi IBM Maximo",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Proses penyusunan draf kajian implementasi IBM Maximo. 05 Jun 26 : Permintaan daftar data aplikasi. 11 jun 26: Pembahasan draft awal. 29 Juni 2026: Sudah dilakukan review internal ZT.",
    keyIssue: "Kroscek kembali sistem serupa IBM Maximo, buat rekomendasi pros and cons. Membutuhkan data pendukung dari unit teknis (Sarana dan Prasarana).",
    actionPlan: "Pendalaman kondisi eksisting dan permintaan data ke unit teknis.",
    deadline: "2026-07-01",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://canva.link/0mr7avcoe4v8qu7",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 22,
    topic: "Evaluasi & Usulan Probis KALOG terkait penguasaan/inbreng sarana (aktiva)",
    cluster: "Strategic Transformation",
    owner: "DN, DR",
    ztRole: "Owner",
    strategicImpact: "Kalog segera menjadi BUPS dan sarana bisa dialihkan",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "4 Juni 2026: Pembahasan proses pengalihan aset. 9 Juni 2026: KALOG & ZT diskusi, permohonan Dewan Komisaris KALOG, identifikasi 3 Train Set CC206 & GD54. 26 Juni: masih dibuat tim ZTI.",
    keyIssue: "DZ minta percepatan agar Kalog segera menjadi BUPS dan sarana bisa dialihkan sehingga divisi MRO memiliki customer. Sedangkan proses inbreng sendiri memakan waktu 28 minggu.",
    actionPlan: "Kajian internal yang akan disampaikan ke DZ terkait kondisi dan proses. 03 Jul 26 : Plan melakukan paparan minggu depan.",
    deadline: "2026-07-01",
    decisionNeeded: "Yes",
    dzIntervention: "Inbreng & BUPS Acceleration Approval",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/f/448498648",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 23,
    topic: "Pembentukan Divisi Properti",
    cluster: "Strategic Transformation",
    owner: "DH",
    ztRole: "Monitoring",
    strategicImpact: "Terbentuknya divisi properti",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "Kamis, 21 Mei 2026 pembahasan konsep SO dengan SGP.",
    keyIssue: "Masih ada fungsi yang beririsan antara unit eksisting (CCC dan KAPM) dengan draft fungsi divisi properti yang telah disampaikan",
    actionPlan: "Monitoring progres yang dilakukan oleh SC, SG, HC. ZT akan membuat kajian internal. 03 Jul 26 : Follow Up ke unit terkait",
    deadline: "",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/f/448287442",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 24,
    topic: "Merger RMU dan Kawisata",
    cluster: "Strategic Transformation",
    owner: "DC",
    ztRole: "Monitoring",
    strategicImpact: "Pembentukan perusahaan merger RMU-Kawisata",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "Pengumuman publik 30 Mei. Badan hukum terbentuk 1 Juli. 9 Juni: Rapat BOD, setuju merger, struktur RMU sebagai basis utama. 26 Juni: Legal Day One 7 Juli 2026.",
    keyIssue: "ZT tidak di masukkan ke dalam grup koordinasi dengan ISM, RMU, Kawisata dan konsultan. proses bisnis heritage di Kawisata perlu di konfirmasi.",
    actionPlan: "Monitoring progres yang dilakukan oleh IS, HC. 03 Jul 26 : Plan melakukan pembahasan internal untuk membuat draft kajian.",
    deadline: "2026-07-01",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/f/450869764",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 25,
    topic: "Sinkronisasi streamlining Kawista ke RMU terkait penghapusan bisnis yang berkaitan dengan sarana kereta",
    cluster: "Strategic Transformation",
    owner: "DS, DH",
    ztRole: "Owner",
    strategicImpact: "Kawista tidak mempunyai bisnis kereta",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Penyusunan draft kajian Sinkronisasi streamlining Kawista ke RMU terkait pengalihan bisnis Kereta wisata dari KA Wisata ke KAI",
    keyIssue: "Belum ada update",
    actionPlan: "Penyusunan draft kajian Sinkronisasi streamlining",
    deadline: "2026-07-01",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/oDwrszQG5EfMPpB",
    notes: "Update Terakhir: Jumat, 26 Juni 2026"
  },
  {
    no: 26,
    topic: "Konektivitas Pelabuhan Tanjung Priok",
    cluster: "Strategic Transformation",
    owner: "DF",
    ztRole: "Monitoring",
    strategicImpact: "Peraturan dari pemerintah (Perpres, PP, Permen dll) terkait konektivitas KA dan pelabuhan terbit",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "Sedang menghitung nilai manfaat ekonomi modal shifting dari truk ke KA oleh unit CM. 24 Juni: semifinal sebelum ke Menko Infra. 22 Jun: PT BLP siap aktifkan dengan 5 GD, simulasi 2 opsi loko, pola operasi tarif matang.",
    keyIssue: "Kajian belum detail. PIC belum jelas",
    actionPlan: "Mengkoordinasikan dengan pihak CM perihal materi kajian nilai manfaat",
    deadline: "2026-04-18",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/AbTifG6WFCfSc2P",
    notes: "Update Terakhir: Senin, 22 Juni 2026"
  },
  {
    no: 27,
    topic: "Konektivitas Pelabuhan KIT Batang",
    cluster: "Strategic Transformation",
    owner: "DF",
    ztRole: "Monitoring",
    strategicImpact: "Konsep, Target, Action Plan",
    phase: "Kajian",
    progress: 0,
    statusTracker: "Red",
    currentMilestone: "18 Juni 2026 : Dokumen final teknis dibahas. Benchmarking sepakat ke Tiongkok biaya mandiri. SPJT sampaikan perlu assement detail Weleri Port. Belum ada keputusan rekomendasi konsultan (KIT & SPJT usul Big 4, Pelindo lokal).",
    keyIssue: "Antar perusahaan masih berbeda pendapat mengenai rekomendasi konsultan yang akan digunakan.",
    actionPlan: "Unit ZT menginisiasi kegiatan benchmark internal dengan melibatkan unit SG, ZL, dan tim DI, tentative nya tanggal 29 Juni 2026",
    deadline: "2026-12-31",
    decisionNeeded: "Yes",
    dzIntervention: "Consultant Recommendation Decision",
    ztPic: "ZTS",
    confidence: "Medium",
    strategicFit: "High",
    priority: "High",
    documentLink: "https://cloud.kai.id/s/AbTifG6WFCfSc2P",
    notes: "Update Terakhir: Jumat, 3 Juli 2026"
  },
  {
    no: 28,
    topic: "pemantauan inisiatif strategis PO-1 streamlining dan BUPP",
    cluster: "Strategic Transformation",
    owner: "",
    ztRole: "Contributing",
    strategicImpact: "Memantau inisiatif strategis PO-1 streamlining dan BUPP",
    phase: "Ideation",
    progress: 0,
    statusTracker: "Yellow",
    currentMilestone: "Inisiasi program pemantauan.",
    keyIssue: "",
    actionPlan: "",
    deadline: "",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "",
    notes: "Tanggal Update: Senin, 6 Juli 2026"
  },
  {
    no: 29,
    topic: "Pembentukan BUPP",
    cluster: "Strategic Transformation",
    owner: "",
    ztRole: "Contributing",
    strategicImpact: "Hasil kajian konsultan BUPP, peraturan dari pemerintah terkait BUPP terbit, SO dan Perdir organ BUPP terbit",
    phase: "Execution",
    progress: 0,
    statusTracker: "Green",
    currentMilestone: "11 Juni 2026: Penyusunan sirkulir persetujuan IP dana untuk konsultan. Konsultan: 1 proses validasi. 26 Juni: Usulan rencana pengadaan konsultan belum dibahas di BoD Meeting terakhir.",
    keyIssue: "Unit ZT secara legal adalah project owner sesuai inisiatif strategis RJPP. tim SC akan berperan sebagai organizing comitee melalui PMO",
    actionPlan: "Unit ZT memonitor dan membantu penyelesaian pemilihan konsultan BUPP",
    deadline: "2026-10-31",
    decisionNeeded: "No",
    dzIntervention: "",
    ztPic: "ZTI",
    confidence: "Medium",
    strategicFit: "Medium",
    priority: "Medium",
    documentLink: "https://cloud.kai.id/s/88XiGtgsebTnmD7",
    notes: "Update Terakhir: Senin, 6 Juli 2026"
  }
];

export const initialLogs: Omit<MeetingLog, "id">[] = [
  {
    programId: "example-1",
    programTitle: "Benchmarking Konektivitas Pelabuhan (KIT Batang) ke China",
    meetingDate: "2026-06-11 14:30",
    notes: "Koordinasi nota diplomatik ke Kemenhub RRT untuk memfasilitasi benchmarking pelabuhan di China.",
    previousStatus: "Yellow",
    newStatus: "Yellow",
    previousProgress: 0,
    newProgress: 0,
    recordedBy: "ZTS Executive Team"
  }
];
